package com.anwardev.booksocialnetwork.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class BooktestingAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBooktestingAllPropertiesEquals(Booktesting expected, Booktesting actual) {
        assertBooktestingAutoGeneratedPropertiesEquals(expected, actual);
        assertBooktestingAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBooktestingAllUpdatablePropertiesEquals(Booktesting expected, Booktesting actual) {
        assertBooktestingUpdatableFieldsEquals(expected, actual);
        assertBooktestingUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBooktestingAutoGeneratedPropertiesEquals(Booktesting expected, Booktesting actual) {
        assertThat(actual)
            .as("Verify Booktesting auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBooktestingUpdatableFieldsEquals(Booktesting expected, Booktesting actual) {
        assertThat(actual)
            .as("Verify Booktesting relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getLastname()).as("check lastname").isEqualTo(expected.getLastname()))
            .satisfies(a -> assertThat(a.getEmail()).as("check email").isEqualTo(expected.getEmail()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBooktestingUpdatableRelationshipsEquals(Booktesting expected, Booktesting actual) {
        // empty method
    }
}
